config/routes.rb
Bugaboo::Application.routes.draw do

  root :to => 'home#index'
  resource :sessions, :only => [ :create, :new, :destroy ]
  resources :password_resets, :only => [ :create, :edit, :new, :update ]
  resources :projects
  resources :bugs
  resources :users

  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/login' => 'sessions#new', :as => 'login'

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_and_belongs_to_many :users

  attr_accessible :name, :is_active

  validates :name, :presence => true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :find_project, :only => [:edit, :update, :destroy]

  def index
    authorize! :read, Project
    @projects = Project.all

    respond_to do |format|
      format.html
      format.json  { render :json => @projects }
    end
  end

  def show
    authorize! :read, Project
    @project = Project.find(params[:id])

    render :json => @project
  end

  def edit
    authorize! :edit, @project
  end

  def update
    authorize! :update, @project
    if @project.update_attributes(params[:project])
      redirect_to projects_url, :notice => "#{@project.name} was saved!"
    else
      render 'edit'
    end
  end

  def new
    @project = Project.new
    authorize! :new, @project
  end

  def create
    @project = Project.new
    authorize! :create, @project
    @project.attributes = params[:project]

    if @project.save
      redirect_to projects_url, :notice => "#{@project.name} was created!"
    else
      render 'new'
    end
  end

  def destroy
    authorize! :destroy, @project
    @project.destroy
    redirect_to projects_url, :notice => "Successfully deleted"
  end
  private

  def find_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<%= form_for @project  do |f| %>
  <% if @project.errors.any? %>
   <div class="error_messages">
     <h2>Form is invalid</h2>
     <ul>
       <% for message in @project.errors.full_messages %>
         <li><%= message %></li>
       <% end %>
     </ul>
    </div>
  <% end %>
  <div class="form-row">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-row">
    <%= f.label :is_active %>
    <%= f.check_box :is_active %>
  </div>
  <div class="form-row">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <td>
    <%= link_to project.name, edit_project_path(project) %>
  </td>
  <td>
    <%= project.created_at %>
  </td>
  <td>
    <%= link_to "Delete", project_path(project), :method => :delete %>
  </td>
</tr>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render 'form' %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<%= link_to "Add Project", new_project_path, :class => 'add-btn'%>
<table>
  <thead>
    <th>Name</th>
    <th>Created At</th>
    <th></th>
  </thead>
  <tbody>
    <%= render :partial => 'project', :collection => @projects %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render 'form' %>