config/routes.rb
Bugaboo::Application.routes.draw do

  root :to => 'home#index'
  resource :sessions, :only => [ :create, :new, :destroy ]
  resources :password_resets, :only => [ :create, :edit, :new, :update ]
  resources :projects
  resources :bugs
  resources :users

  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/login' => 'sessions#new', :as => 'login'

end

app/models/bug.rb
class Bug < ActiveRecord::Base

  belongs_to :project
  belongs_to :author, :class_name => 'User', :foreign_key => 'author_id'
  belongs_to :assigned, :class_name => 'User', :foreign_key => 'user_assigned_id'

  validates :summary, :author_id, :current_state, :severity, :project_id, :presence => true

  STATES = %w(Open Closed)
  SEVERITIES = ["Meh", "Pretty bad", "Sound the alarm"]

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController

  helper_method :sort_column, :sort_direction

  before_filter :find_bug, :only => [:edit, :update, :destroy]
  before_filter :fetch_projects, :only => [:edit, :update, :new, :create]
  before_filter :fetch_users, :only => [:edit, :update, :new, :create]

  def index
    authorize! :read, Bug

    page            = params[:page]            ||= 1
    per_page        = params[:per_page]        ||= 10

    @bugs = Bug.order("#{sort_column} #{sort_direction}")
        .paginate(:page => page, :per_page => per_page)
        .all

    respond_to do |format|
      format.html
      format.json  { render :json => @bugs }
    end
  end

  def show
    authorize! :read, Bug

    @bug = Bug.find(params[:id])
    render :json => @bug
  end

  def edit
    authorize! :edit, @bug
  end

  def update
    authorize! :update, @bug
    if @bug.update_attributes(params[:bug])
      redirect_to bugs_url, :notice => "Bug saved"
    else
      render 'edit'
    end
  end

  def new
    @bug = Bug.new
    authorize! :new, @bug
  end

  def create
    @bug = Bug.new
    authorize! :create, @bug
    @bug.attributes = params[:bug]
    @bug.author_id = current_user.id

    if @bug.save
      redirect_to bugs_url, :notice => "Bug was created!"
    else
      render 'new'
    end
  end

  def destroy
    authorize! :destroy, @bug
    @bug.destroy
    redirect_to bugs_url, :notice => "Successfully deleted"
  end

  private

  def find_bug
    @bug = Bug.find(params[:id])
  end

  def fetch_projects
    @projects = current_user.projects.collect {|p| [p.name, p.id] } if current_user
  end

  def fetch_users
    @users = User.all.collect {|u| [ u.full_name, u.id ] }
  end

  def sort_column
    Bug.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/views/bugs/_bug.html.erb
<tr>
  <td>
    <%= bug.id %>
  </td>
  <td>
    <%= link_to bug.summary, edit_bug_path(bug) %>
  </td>
  <td>
    <%= bug.current_state %>
  </td>
  <td>
    <%= bug.severity %>
  </td>
  <td>
    <%= bug.author.full_name %>
  </td>
  <td>
    <% if bug.assigned %>
      <%= bug.assigned.full_name %>
    <% else %>
      Not Assigned
    <% end %>
  </td>
  <td>
    <%= bug.created_at %>
  </td>
  <td>
    <%= link_to "Delete", bug_path(bug), :method => :delete %>
  </td>
</tr>

app/views/bugs/_form.html.erb
<%= form_for @bug  do |f| %>
  <% if @bug.errors.any? %>
   <div class="error-messages">
     <h2><marquee>Form is invalid</marquee></h2>
     <ul>
       <% for message in @bug.errors.full_messages %>
         <li><%= message %></li>
       <% end %>
     </ul>
   </div>
  <% end %>
  <div class="form-row">
    <%= f.label :summary %>
    <%= f.text_field :summary %>
  </div>
  <div class="form-row">
    <%= f.label :steps_to_reproduce %>
    <%= f.text_area :steps_to_reproduce %>
  </div>
  <div class="form-row">
    <%= f.label :user_assigned_id, "Assign to" %>
    <%= select(:bug, :user_assigned_id, @users, {:prompt => 'Assign to user'}) %>
  </div>
  <div class="form-row">
    <%= f.label :project_id, 'Project' %>
    <%= select(:bug, :project_id, @projects, {:prompt => 'Assign to project'}) %>
  </div>
  <div class="form-row">
    <%= f.label :current_state %>
    <%= select(:bug, :current_state, Bug::STATES) %>
  </div>
  <div class="form-row">
    <%= f.label :severity %>
    <%= select(:bug, :severity, Bug::SEVERITIES) %>
  </div>
  <div class="form-row button-row">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h2>Edit Bug</h2>
<%= render 'form' %>

app/views/bugs/index.html.erb
<h2>Bugs</h2>
<%= link_to "Add Bug", new_bug_path, :class => 'add-btn' %>
<table>
  <thead>
    <th><%= sortable "id", "Ticket Number" %></th>
    <th><%= sortable "summary" %></th>
    <th><%= sortable "current_state", "State" %></th>
    <th><%= sortable "severity" %></th>
    <th><%= sortable "author_id", "Creator" %></th>
    <th><%= sortable "user_assigned_id", "Assigned" %></th>
    <th><%= sortable "created_at", "Created" %></th>
    <th></th>
  </thead>
  <tbody>
    <%= render :partial => 'bug', :collection => @bugs %>
  </tbody>
</table>
<%= will_paginate @bugs %>

app/views/bugs/new.html.erb
<h2>New Bug</h2>
<%= render 'form' %>